### ISSUE TITLE
Rename to include “rails”?

### ISSUE THREAD

**Issue by sindrenm** [hyperoslo/angular_template#1]
I'd like to mention Rails in the name of this repository, as it is a Rails template which includes configuration with Angular. What do you think? :smiley: 

Something like _rails_angular_template_ maybe?

**Comment by ohenrik** [comment]
Agree, however i tried to keep the name short as you would have to type the name into the `-m` option.  Should we change it to `rails_angular_template` or should we try to find something shorter like `rails_ng_tmpl`. Or maybe it does not mather due to autocomplete.

**Comment by ohenrik** [comment]
Actually i agree completely. Autocomplete would take care of the long name i guess. :D

**Comment by sindrenm** [comment]
Awesome. :grinning:
